--- !ditz.rubyforge.org,2008-03-06/project 
name: knitting
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: knitting
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: Go-live
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-07-13 01:02:19.669904 Z
    - Michael Melanson <michael@codeshack.ca>
    - created
    - When this release is complete, launch to the public.
- !ditz.rubyforge.org,2008-03-06/release 
  name: Backlog
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-07-13 01:04:01.446562 Z
    - Michael Melanson <michael@codeshack.ca>
    - created
    - ""
